#!/bin/env sh
# simple test runner script

log=test/mocha.log

# start meteor
cd app
meteor &
pid=$!
cd ..
echo -e "Meteor started: ${pid}\n"

# run tests
mocha $* &> $log

# print (useful) results
grep -vE '(anonymous|async task)' $log

# kill meteor
kill -9 $pid && echo "Meteor killed."
